services:
  db:
    image: postgres:18-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: fundacion_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build:
      context: ./fundacion-backend
      dockerfile: Dockerfile.dev
    container_name: springboot_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fundacion_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secretpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./fundacion-backend:/app
      - maven_repo:/root/.m2
    depends_on:
      - db

  frontend:
    build:
      context: ./fundacion-frontend
      dockerfile: Dockerfile.dev
    container_name: react_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./fundacion-frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
  maven_repo:
